x = -pi:0.2:pi;
y = 0:0.1:1;
[X,Y] = meshgrid(x,y);
Z = exp(x).*sin(Y) + exp(-X).*cos(Y);
subplot(3,1,1);
title("Z = exp(x).*sin(Y) + exp(-X).*cos(Y)");
surf(X,Y,Z);
colorbar;
xlabel("X");
ylabel("Y");
zlabel("Z");
subplot(3,1,2);
surfl(X,Y,Z, [1,0,0]);
shading interp;
colorbar;
xlabel("X");
ylabel("Y");
zlabel("Z");
subplot(3,1,3);
mesh(X,Y,Z);
colorbar;
xlabel("X");
ylabel("Y");
zlabel("Z");